"""
Copyright (C) 2019-2020 Sergio G Rodrigo <sergut@unizar.es>

**Important:** 
*IrisFDTD* is licensed under the AGPL and it is free to use. 
if you are using, or plan to use this example, specially if it is 
for research or academic purposes, please send an email with your name, 
institution and a brief description of your interest for this program. 
"""

'''
 Generates a video with the time evolution of the electromagnetic fields
'''
import IrisFDTD_time_evolution as fdtd_time
if(True):
    path="./example_1/" 
    mesh=5.0e-3  # in microns (q in inputFDTD)
    videoname= "IrisFDTD-academic"  
 

filename = "Y_SDL_E" # as generated by IrisFDTD
ext=".e"
title="Time %.1f (fs)"
initime=0.0
deltatime= 0.00770333*25962/50   # deltatime=dt*itmax/no_downloads
                                 # dt in log.dat (dt in fs)
                                 # itmax in time step units in inputFDTD 
                                 # no_downloads in inputFDTD. 
nx,nz = 300,250  # nx=sxi*SDL_copy_no ; nz = szf-szi  in inputFDTD
initime=2        # Init iteration
endtime=50      # no_downloads in inputFDTD. 
Z=None

vmin=0.0 ; vmax=1.0 # Escale
labelcmap="$|E|$\n"


s=fdtd_time.fdtdEMt(initime,endtime,nx,nz,path,filename,ext)
Z = s.setpyplotformat()
s.createmovie(Z,"XZ",videoname,title,labelcmap=labelcmap,unit_cells=1,mesh_size=mesh,
              ini=initime,delta=deltatime,vmin=vmin,vmax=vmax)

del Z,s
